# Generated by Django 4.1.1 on 2022-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='intopost',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='intopost',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
