# Generated by Django 4.1.1 on 2022-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_intopost_author_intopost_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='intopost',
            name='time_to_reat',
            field=models.CharField(default='', help_text='add only numbers', max_length=3),
        ),
    ]
