# Generated by Django 4.1.1 on 2022-09-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_intopost_time_to_reat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intopost',
            old_name='time_to_reat',
            new_name='time_to_read',
        ),
    ]
