# Generated by Django 4.1.1 on 2022-09-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_intopost_sources_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='intopost',
            name='header',
            field=models.CharField(default='', help_text='max length 200s', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='max length 100s', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='max length 100s', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(help_text='max length 100s', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(help_text='max length 500s', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(help_text='max length 50s', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.CharField(help_text='max length 150s', max_length=150),
        ),
        migrations.AlterField(
            model_name='intopost',
            name='author',
            field=models.CharField(default='', help_text='max length 50s', max_length=50),
        ),
        migrations.AlterField(
            model_name='intopost',
            name='country',
            field=models.CharField(default='', help_text='max length 50s', max_length=50),
        ),
        migrations.AlterField(
            model_name='intopost',
            name='name',
            field=models.CharField(help_text='max length 100s', max_length=100),
        ),
        migrations.AlterField(
            model_name='intopost',
            name='sources',
            field=models.TextField(default='', help_text='max length 200s', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', help_text='max length 200s', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='max length 200s', max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='max length 200s', max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='max length 100s', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='max length 100s', max_length=100),
        ),
    ]
