# Generated by Django 4.1.1 on 2022-09-18 14:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_intopost_under_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intopost',
            name='allpost',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='intopost',
            name='sources',
            field=ckeditor.fields.RichTextField(default='', help_text='max length 200s', max_length=500),
        ),
    ]
